name: Build, Lint and Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - master
      - develop

    paths:
      - 'src/**'
      - 'Configuration/**'
      - 'webpack.dev.config.js'
      - 'webpack.prod.config.js'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Bundle
      run: npm run build

    - name: copy default document
      run: cp ./src/index.html ./dist/index.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  sync:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: Set bucket
      uses: haya14busa/action-cond@v1
      id: set_bucket
      with:
        cond: ${{ github.ref == 'refs/heads/master' }}
        if_true: ${{ secrets.AWS_S3_BUCKET }}
        if_false: ${{ secrets.AWS_S3_TEST_BUCKET }}

    - name: S3 Sync HTML
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '*' --include '*.html' --acl 'public-read' --delete
      env:
        AWS_S3_BUCKET: ${{ set_bucket }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: './'

    - name: S3 Sync JS
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '*' --include '*.js' --acl 'public-read' --content-type application/javascript --content-encoding gzip --delete
      env:
        AWS_S3_BUCKET: ${{ set_bucket }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: './'