name: Build, Lint and Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Bundle
      run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

  sync:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: S3 Sync HTML
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude "*" --include "*.html" --acl "public-read" --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: './dist'
        DEST_DIR: '/'

    - name: S3 Sync JS
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude "*" --include "*.js" --acl "public-read" --content-type application/javascript --content-encoding gzip --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: './dist'
        DEST_DIR: '/'